server {
    listen 80;
    server_name localhost;

    location / {
        # 网站根目录
        root /usr/share/nginx/html;
        # 默认首页
        index index.html;
        # 路由回退 (防止刷新 404)
        try_files $uri $uri/ /index.html;

        # === 核心：密码锁配置 ===
        auth_basic "Restricted Access - Titan Lite System";
        auth_basic_user_file /etc/nginx/.htpasswd;
    }
}